// The shared category rail. Mobile imports the same list in its batch.
export const CATEGORIES: { key: string; label: string; words: string[] }[] = [
  { key: "innovation", label: "Innovation", words: [] },
  { key: "comedy", label: "Comedy", words: ["comedy", "funny", "joke", "skit", "lol", "haha"] },
  { key: "music", label: "Music", words: ["music", "song", "album", "artist", "beat", "zimdancehall", "sungura", "gospel"] },
  { key: "news", label: "News", words: ["news", "breaking", "report", "announced"] },
  { key: "sports", label: "Sports", words: ["sport", "match", "game", "team", "league"] },
  { key: "football", label: "Football", words: ["football", "soccer", "goal", "warriors", "premier"] },
  { key: "business", label: "Business", words: ["business", "startup", "entrepreneur", "company", "revenue"] },
  { key: "finance", label: "Finance", words: ["finance", "money", "investment", "bank", "forex", "crypto"] },
  { key: "technology", label: "Technology", words: ["tech", "technology", "software", "app", "coding", "ai"] },
  { key: "science", label: "Science", words: ["science", "research", "study", "physics", "biology"] },
  { key: "education", label: "Education", words: ["education", "school", "learning", "exam", "student"] },
  { key: "universities", label: "Universities", words: ["university", "uz", "nust", "msu", "campus", "college"] },
  { key: "fashion", label: "Fashion", words: ["fashion", "style", "outfit", "wear", "drip"] },
  { key: "beauty", label: "Beauty", words: ["beauty", "makeup", "skincare", "hair"] },
  { key: "food", label: "Food", words: ["food", "recipe", "cooking", "sadza", "restaurant", "meal"] },
  { key: "travel", label: "Travel", words: ["travel", "trip", "visit", "vacation", "victoria falls"] },
  { key: "cars", label: "Cars", words: ["car", "vehicle", "toyota", "honda", "drive", "ex-jap"] },
  { key: "property", label: "Property", words: ["property", "house", "rent", "stand", "apartment", "real estate"] },
  { key: "gaming", label: "Gaming", words: ["gaming", "game", "fifa", "playstation", "xbox"] },
  { key: "health", label: "Health & Fitness", words: ["health", "fitness", "gym", "workout", "wellness"] },
  { key: "culture", label: "Culture", words: ["culture", "tradition", "heritage", "shona", "ndebele"] },
  { key: "history", label: "History", words: ["history", "historic", "chimurenga", "great zimbabwe"] },
  { key: "agriculture", label: "Agriculture", words: ["agriculture", "farming", "farm", "tobacco", "maize", "harvest"] },
  { key: "creators", label: "Creators", words: ["creator", "content", "vlog", "youtube", "tiktok"] },
  { key: "photography", label: "Photography", words: ["photography", "photo", "camera", "shot"] },
  { key: "art", label: "Art", words: ["art", "artist", "painting", "drawing", "design"] },
  { key: "lifestyle", label: "Lifestyle", words: ["lifestyle", "life", "daily", "routine", "relationship"] },
  { key: "diaspora", label: "Diaspora", words: ["diaspora", "abroad", "uk", "usa", "south africa", "remit"] },
  { key: "market", label: "Market", words: ["market", "selling", "buy", "sale", "listing", "price"] },
  { key: "careers", label: "Careers", words: ["career", "job", "hiring", "cv", "interview", "internship"] },
];