'use client';

/**
 * The presentation builder. Everything on these slides came off a real desk:
 * the numbers are the ones the admin was looking at, the tables carry the
 * filter state they were under, and every deck ends with the context block that
 * makes it trustworthy - where it came from, who made it and when.
 * Print produces one slide per page, which is the PDF.
 */

import { useEffect, useMemo, useRef, useState } from 'react';
import { csv, downloadText, maskRow, slug, stamp, trayClear, trayRead, trayRemove, whenLong, type TrayItem } from '@/lib/share';

type Audience = 'Internal' | 'Management' | 'External sanitized';

type Slide =
  | { kind: 'cover'; title: string; sub: string }
  | { kind: 'summary'; stats: { label: string; value: string; note: string }[] }
  | { kind: 'stat'; item: TrayItem }
  | { kind: 'table'; item: TrayItem }
  | { kind: 'note'; item: TrayItem }
  | { kind: 'context'; lines: { label: string; value: string }[] };

const NAVY = '#0B1E3D';

export default function PresentBuilder({ by, role, env }: { by: string; role: string; env: string }) {
  const [items, setItems] = useState<TrayItem[]>([]);
  const [drop, setDrop] = useState<Record<string, boolean>>({});
  const [title, setTitle] = useState('Platinum Circles Operations');
  const [range, setRange] = useState('');
  const [audience, setAudience] = useState<Audience>('Internal');
  const [commentary, setCommentary] = useState('');
  const [dark, setDark] = useState(true);
  const [at, setAt] = useState(0);
  const [live, setLive] = useState(false);
  const deck = useRef<HTMLDivElement | null>(null);

  useEffect(() => { setItems(trayRead()); }, []);

  const kept = items.filter(i => !drop[i.id]);
  const sanitize = audience === 'External sanitized';

  const slides: Slide[] = useMemo(() => {
    const out: Slide[] = [];
    const pages = Array.from(new Set(kept.map(i => i.page)));
    out.push({ kind: 'cover', title, sub: [range.trim(), pages.join(' \u00b7 ')].filter(Boolean).join('  \u2014  ') || 'Operations briefing' });
    const stats = kept.filter(i => i.kind === 'stat').map(i => ({ label: i.title, value: i.stat?.value || '', note: i.stat?.note || i.page }));
    if (stats.length > 0) out.push({ kind: 'summary', stats });
    for (const i of kept) {
      if (i.kind === 'stat') out.push({ kind: 'stat', item: i });
      else if (i.kind === 'table') out.push({ kind: 'table', item: i });
      else out.push({ kind: 'note', item: i });
    }
    if (commentary.trim()) out.push({ kind: 'note', item: { id: 'findings', kind: 'note', title: 'Key findings', page: title, path: '/present', createdAt: new Date().toISOString(), note: { text: commentary } } });
    out.push({ kind: 'context', lines: [
      { label: 'Generated from', value: 'Platinum Circles Operations' },
      { label: 'Desks', value: pages.join(', ') || 'none' },
      { label: 'Date range', value: range.trim() || 'as shown on the desks' },
      { label: 'Audience', value: audience },
      { label: 'Generated by', value: by + ' (' + role.replace(/_/g, ' ') + ')' },
      { label: 'Generated at', value: whenLong() },
      { label: 'Environment', value: env },
    ] });
    return out;
  }, [kept, title, range, audience, commentary, by, role, env]);

  const total = slides.length;
  const cur = Math.min(at, total - 1);

  useEffect(() => {
    if (!live) return;
    function key(e: KeyboardEvent) {
      if (e.key === 'ArrowRight' || e.key === ' ') { e.preventDefault(); setAt(a => Math.min(a + 1, total - 1)); }
      else if (e.key === 'ArrowLeft') { e.preventDefault(); setAt(a => Math.max(a - 1, 0)); }
      else if (e.key === 'Escape') { setLive(false); if (document.fullscreenElement) void document.exitFullscreen(); }
    }
    window.addEventListener('keydown', key);
    return () => window.removeEventListener('keydown', key);
  }, [live, total]);

  function present() {
    setLive(true);
    void deck.current?.requestFullscreen?.();
  }

  function exportTables() {
    const tables = kept.filter(i => i.kind === 'table' && i.table);
    if (tables.length === 0) return;
    for (const t of tables) {
      const cols = t.table!.columns;
      const rows = sanitize ? t.table!.rows.map(r => maskRow(cols, r)) : t.table!.rows;
      downloadText(slug(t.page + '-' + t.title) + '-' + stamp() + '.csv', 'text/csv', csv(cols, rows));
    }
  }

  function exportJson() {
    downloadText(slug(title) + '-' + stamp() + '.json', 'application/json', JSON.stringify({
      title, range, audience, generatedBy: by, generatedAt: new Date().toISOString(), environment: env,
      items: kept.map(i => (sanitize && i.table ? { ...i, table: { ...i.table, rows: i.table.rows.map(r => maskRow(i.table!.columns, r)) } } : i)),
      commentary,
    }, null, 2));
  }

  if (items.length === 0) {
    return (
      <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--bg)', color: 'var(--txt)' }}>
        <div style={{ textAlign: 'center', maxWidth: 460, padding: 24 }}>
          <div style={{ fontSize: 21, color: 'var(--txt-strong)' }}>Nothing collected yet</div>
          <p style={{ marginTop: 10, fontSize: 13, lineHeight: 1.6, color: 'rgba(var(--on),0.5)' }}>
            Open any desk and use the plus on a number, the share menu on a table, or Add a note from the topbar.
            Everything you collect lands here and becomes a deck, a briefing or a spreadsheet.
          </p>
          <a href="/dashboard" style={{ display: 'inline-block', marginTop: 18, padding: '9px 16px', borderRadius: 9, fontSize: 12.5, fontWeight: 700, textDecoration: 'none', background: 'var(--accent)', color: 'var(--accent-ink)' }}>Back to the dashboard</a>
        </div>
      </div>
    );
  }

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', color: 'var(--txt)' }}>

      <header className="pc-no-print" style={{ position: 'sticky', top: 0, zIndex: 30, display: 'flex', alignItems: 'center', gap: 12, height: 56, padding: '0 18px', background: 'var(--topbar)', backdropFilter: 'blur(26px)', borderBottom: '1px solid rgba(var(--on),0.10)' }}>
        <a href="/dashboard" style={{ display: 'flex', alignItems: 'center', gap: 9, textDecoration: 'none' }}>
          <img src="/pearl.png" alt="" className="pc-mark" style={{ width: 26, height: 26, objectFit: 'contain' }} />
          <span style={{ fontSize: 13, color: 'var(--txt-strong)' }}>Presentation builder</span>
        </a>
        <span className="pc-num" style={{ fontSize: 11, color: 'rgba(var(--on),0.34)' }}>{total} slides</span>
        <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 8 }}>
          <button type="button" onClick={exportTables} style={ghost}>Export data</button>
          <button type="button" onClick={exportJson} style={ghost}>Export JSON</button>
          <button type="button" onClick={() => window.print()} style={ghost}>Download PDF</button>
          <button type="button" onClick={present} style={solid}>Present</button>
        </div>
      </header>

      <div style={{ display: 'grid', gridTemplateColumns: '182px 1fr 296px', alignItems: 'start', gap: 0, minHeight: 'calc(100vh - 56px)' }}>

        <aside className="pc-no-print pc-rail-scroll" style={{ position: 'sticky', top: 56, height: 'calc(100vh - 56px)', overflowY: 'auto', padding: 12, borderRight: '1px solid rgba(var(--on),0.09)' }}>
          {slides.map((s, i) => (
            <button key={i} type="button" onClick={() => setAt(i)}
              style={{
                display: 'block', width: '100%', textAlign: 'left', marginBottom: 8, padding: '9px 10px',
                borderRadius: 9, cursor: 'pointer', fontSize: 11.4, lineHeight: 1.35,
                border: '1px solid ' + (i === cur ? 'rgba(var(--accent-rgb),0.4)' : 'rgba(var(--on),0.09)'),
                background: i === cur ? 'rgba(var(--on),0.05)' : 'transparent',
                color: i === cur ? 'var(--txt-strong)' : 'rgba(var(--on),0.5)',
              }}>
              <span className="pc-num" style={{ fontSize: 9.5, color: 'rgba(var(--on),0.32)' }}>{String(i + 1).padStart(2, '0')}</span>
              <span style={{ display: 'block', marginTop: 3, fontWeight: 600 }}>{slideTitle(s)}</span>
            </button>
          ))}
        </aside>

        <main ref={deck} style={{ padding: live ? 0 : '22px 20px 40px', background: live ? (dark ? NAVY : '#FFFFFF') : 'transparent' }}>
          {live ? (
            <div onClick={() => setAt(a => Math.min(a + 1, total - 1))} style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' }}>
              <div style={{ width: 'min(1180px, 92vw)' }}>{renderSlide(slides[cur], dark, sanitize)}</div>
            </div>
          ) : (
            <div className="pc-deck">
              {slides.map((s, i) => (
                <section key={i} className="pc-slide" onClick={() => setAt(i)}
                  style={{
                    marginBottom: 18, borderRadius: 14, overflow: 'hidden',
                    border: '1px solid ' + (i === cur ? 'rgba(var(--accent-rgb),0.35)' : 'rgba(var(--on),0.10)'),
                    background: dark ? NAVY : '#FFFFFF',
                    boxShadow: i === cur ? '0 12px 34px rgba(0,0,0,0.16)' : 'none',
                  }}>
                  {renderSlide(s, dark, sanitize)}
                </section>
              ))}
            </div>
          )}
        </main>

        <aside className="pc-no-print pc-rail-scroll" style={{ position: 'sticky', top: 56, height: 'calc(100vh - 56px)', overflowY: 'auto', padding: 14, borderLeft: '1px solid rgba(var(--on),0.09)' }}>
          <Field label="Title"><input value={title} onChange={e => setTitle(e.target.value)} style={input} /></Field>
          <Field label="Date range"><input value={range} onChange={e => setRange(e.target.value)} placeholder="1 to 31 August 2026" style={input} /></Field>
          <Field label="Audience">
            <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
              {(['Internal', 'Management', 'External sanitized'] as Audience[]).map(a => (
                <button key={a} type="button" onClick={() => setAudience(a)}
                  style={{ padding: '8px 10px', textAlign: 'left', borderRadius: 8, cursor: 'pointer', fontSize: 11.8, fontWeight: 600,
                    border: '1px solid ' + (audience === a ? 'rgba(var(--accent-rgb),0.4)' : 'rgba(var(--on),0.11)'),
                    background: audience === a ? 'rgba(var(--on),0.05)' : 'transparent',
                    color: audience === a ? 'var(--txt-strong)' : 'rgba(var(--on),0.5)' }}>
                  {a}
                </button>
              ))}
            </div>
            {sanitize ? <p style={hint}>Emails, phone numbers, identifiers, wallet and transaction references are masked in every table and export.</p> : null}
          </Field>
          <Field label="Theme">
            <div style={{ display: 'flex', gap: 6 }}>
              {[{ k: true, l: 'Platinum navy' }, { k: false, l: 'Paper' }].map(t => (
                <button key={String(t.k)} type="button" onClick={() => setDark(t.k)}
                  style={{ flex: 1, padding: '8px 0', borderRadius: 8, cursor: 'pointer', fontSize: 11.5, fontWeight: 600,
                    border: '1px solid ' + (dark === t.k ? 'rgba(var(--accent-rgb),0.4)' : 'rgba(var(--on),0.11)'),
                    background: dark === t.k ? 'rgba(var(--on),0.05)' : 'transparent',
                    color: dark === t.k ? 'var(--txt-strong)' : 'rgba(var(--on),0.5)' }}>{t.l}</button>
              ))}
            </div>
          </Field>
          <Field label="Key findings">
            <textarea value={commentary} onChange={e => setCommentary(e.target.value)} rows={5} placeholder="What should the reader do with this?"
              style={{ ...input, resize: 'vertical', lineHeight: 1.5 }} />
          </Field>
          <Field label={'Collected items (' + items.length + ')'}>
            {items.map(i => (
              <div key={i.id} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '7px 0', borderBottom: '1px solid rgba(var(--on),0.06)' }}>
                <input type="checkbox" checked={!drop[i.id]} onChange={e => setDrop(p => ({ ...p, [i.id]: !e.target.checked }))} />
                <span style={{ flex: 1, minWidth: 0 }}>
                  <span style={{ display: 'block', fontSize: 11.8, fontWeight: 600, color: 'var(--txt)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{i.title}</span>
                  <span style={{ display: 'block', fontSize: 10, color: 'rgba(var(--on),0.34)' }}>{i.page + ' \u00b7 ' + i.kind}</span>
                </span>
                <button type="button" onClick={() => { trayRemove(i.id); setItems(trayRead()); }} title="Remove"
                  style={{ border: 'none', background: 'transparent', cursor: 'pointer', color: 'rgba(var(--on),0.34)', fontSize: 14, lineHeight: 1 }}>&times;</button>
              </div>
            ))}
            <button type="button" onClick={() => { trayClear(); setItems([]); }} style={{ ...ghost, marginTop: 10, width: '100%' }}>Clear everything</button>
          </Field>
        </aside>
      </div>
    </div>
  );
}

function slideTitle(s: Slide): string {
  if (s.kind === 'cover') return s.title;
  if (s.kind === 'summary') return 'Executive summary';
  if (s.kind === 'context') return 'Provenance';
  return s.item.title;
}

function renderSlide(s: Slide, dark: boolean, sanitize: boolean) {
  const ink = dark ? '#FFFFFF' : '#0F1419';
  const dim = dark ? 'rgba(255,255,255,0.58)' : 'rgba(15,20,25,0.55)';
  const line = dark ? 'rgba(255,255,255,0.14)' : 'rgba(15,20,25,0.12)';
  const pad = { padding: '46px 52px', minHeight: 372, display: 'flex', flexDirection: 'column' as const };

  if (s.kind === 'cover') {
    return (
      <div style={{ ...pad, justifyContent: 'center' }}>
        <img src="/pearl.png" alt="" style={{ width: 44, height: 44, objectFit: 'contain', marginBottom: 26 }} />
        <div style={{ fontSize: 40, lineHeight: 1.12, color: ink, letterSpacing: '-0.01em' }}>{s.title}</div>
        <div style={{ marginTop: 14, fontSize: 15, color: dim }}>{s.sub}</div>
      </div>
    );
  }

  if (s.kind === 'summary') {
    return (
      <div style={pad}>
        <SlideHead title="Executive summary" dim={dim} ink={ink} />
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(190px, 1fr))', gap: 18, marginTop: 26 }}>
          {s.stats.map((st, i) => (
            <div key={i} style={{ borderTop: '1px solid ' + line, paddingTop: 14 }}>
              <div style={{ fontSize: 12, color: dim }}>{st.label}</div>
              <div className="pc-num" style={{ marginTop: 8, fontSize: 34, lineHeight: 1, color: ink }}>{st.value}</div>
              <div style={{ marginTop: 8, fontSize: 11, color: dim }}>{st.note}</div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  if (s.kind === 'stat') {
    const st = s.item.stat;
    return (
      <div style={{ ...pad, justifyContent: 'center' }}>
        <SlideHead title={s.item.page} dim={dim} ink={ink} />
        <div style={{ marginTop: 20, fontSize: 17, color: dim }}>{s.item.title}</div>
        <div className="pc-num" style={{ marginTop: 12, fontSize: 74, lineHeight: 1, color: ink }}>{st?.value}</div>
        <div style={{ marginTop: 16, fontSize: 13, color: dim }}>{[st?.delta, st?.note].filter(Boolean).join('  \u00b7  ')}</div>
      </div>
    );
  }

  if (s.kind === 'table') {
    const t = s.item.table;
    const cols = t?.columns || [];
    const rows = (t?.rows || []).slice(0, 12);
    return (
      <div style={pad}>
        <SlideHead title={s.item.page} dim={dim} ink={ink} />
        <div style={{ marginTop: 14, fontSize: 22, color: ink }}>{s.item.title}</div>
        {t && t.filters.length > 0 ? <div style={{ marginTop: 7, fontSize: 11.5, color: dim }}>{t.filters.join('  \u00b7  ')}</div> : null}
        <table style={{ marginTop: 20, width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
          <thead>
            <tr>{cols.map((c, i) => <th key={i} style={{ textAlign: 'left', padding: '0 10px 9px 0', borderBottom: '1px solid ' + line, fontSize: 10.5, fontWeight: 700, letterSpacing: '0.03em', color: dim }}>{c.toUpperCase()}</th>)}</tr>
          </thead>
          <tbody>
            {(sanitize ? rows.map(r => maskRow(cols, r)) : rows).map((r, ri) => (
              <tr key={ri}>{r.map((v, ci) => <td key={ci} style={{ padding: '9px 10px 9px 0', borderBottom: '1px solid ' + line, color: ci === 0 ? ink : dim, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', maxWidth: 220 }}>{v}</td>)}</tr>
            ))}
          </tbody>
        </table>
        {t && t.total > rows.length ? <div style={{ marginTop: 12, fontSize: 11, color: dim }}>Showing {rows.length} of {t.total} matching rows. The full set is in the CSV export.</div> : null}
      </div>
    );
  }

  if (s.kind === 'note') {
    return (
      <div style={{ ...pad, justifyContent: 'center' }}>
        <SlideHead title={s.item.page} dim={dim} ink={ink} />
        <div style={{ marginTop: 16, fontSize: 26, lineHeight: 1.25, color: ink }}>{s.item.title}</div>
        <p style={{ marginTop: 18, fontSize: 16, lineHeight: 1.6, color: dim, whiteSpace: 'pre-wrap', maxWidth: 780 }}>{s.item.note?.text}</p>
      </div>
    );
  }

  return (
    <div style={pad}>
      <SlideHead title="Provenance" dim={dim} ink={ink} />
      <div style={{ marginTop: 22, display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '16px 30px' }}>
        {s.lines.map((l, i) => (
          <div key={i} style={{ borderTop: '1px solid ' + line, paddingTop: 11 }}>
            <div style={{ fontSize: 10.5, fontWeight: 700, letterSpacing: '0.03em', color: dim }}>{l.label.toUpperCase()}</div>
            <div style={{ marginTop: 6, fontSize: 13.5, color: ink }}>{l.value}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

function SlideHead({ title, dim, ink }: { title: string; dim: string; ink: string }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 9 }}>
      <img src="/pearl.png" alt="" style={{ width: 18, height: 18, objectFit: 'contain' }} />
      <span style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.05em', color: dim }}>{title.toUpperCase()}</span>
      <span style={{ flex: 1 }} />
      <span style={{ fontSize: 11, color: ink, opacity: 0.5 }}>Platinum Circles</span>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 16 }}>
      <div style={{ marginBottom: 7, fontSize: 10, fontWeight: 700, letterSpacing: '0.04em', color: 'rgba(var(--on),0.4)' }}>{label.toUpperCase()}</div>
      {children}
    </div>
  );
}

const input: React.CSSProperties = {
  width: '100%', padding: '8px 10px', borderRadius: 8, fontSize: 12, color: 'var(--txt)',
  background: 'rgba(var(--on),0.04)', border: '1px solid rgba(var(--on),0.11)', outline: 'none',
};

const ghost: React.CSSProperties = {
  padding: '7px 12px', borderRadius: 8, cursor: 'pointer', fontSize: 11.6, fontWeight: 600,
  color: 'rgba(var(--on),0.6)', background: 'transparent', border: '1px solid rgba(var(--on),0.11)',
};

const solid: React.CSSProperties = {
  padding: '7px 15px', borderRadius: 8, cursor: 'pointer', fontSize: 11.8, fontWeight: 700,
  color: 'var(--accent-ink)', background: 'var(--accent)', border: 'none',
};

const hint: React.CSSProperties = { marginTop: 8, fontSize: 10.8, lineHeight: 1.5, color: 'rgba(var(--on),0.38)' };
